### ISSUE TITLE
AzureVMCluster fails to start with AttributeError: 'PublicIPAddressesOperations' object has no attribute 'begin_create_or_update'

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-cloudprovider#184]
Reported to me directly by a colleague.

```
Creating scheduler instance
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\dask_cloudprovider\azure\azurevm.py", line 468, in __init__
    super().__init__(**kwargs)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\dask_cloudprovider\generic\vmcluster.py", line 235, in __init__
    super().__init__(**kwargs)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\deploy\spec.py", line 276, in __init__
    self.sync(self._start)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\deploy\cluster.py", line 183, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\utils.py", line 324, in f
    result[0] = yield future
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\dask_cloudprovider\generic\vmcluster.py", line 260, in _start
    await super()._start()
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\deploy\spec.py", line 304, in _start
    self.scheduler = await self.scheduler
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\deploy\spec.py", line 71, in _
    await self.start()
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\dask_cloudprovider\generic\vmcluster.py", line 83, in start
    ip = await self.create_vm()
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\dask_cloudprovider\azure\azurevm.py", line 88, in create_vm
    self.cluster.network_client.public_ip_addresses.begin_create_or_update(
AttributeError: 'PublicIPAddressesOperations' object has no attribute 'begin_create_or_update'
```

**Comment by jacobtomlinson** [comment]
This appears to be because the Azure dependencies are out of date. At some point `create_or_update` was renamed to `begin_create_or_update`. I noticed this when reading SO answers on using the Azure SDK.

To resolve we should set a minimum version on the dependencies.
