### ISSUE TITLE
Problem launching ECSCluster

### ISSUE THREAD

**Issue by jkanche** [dask/dask-cloudprovider#189]
I tried to launch an ECSCluster on AWS but fails with the following message

My command to launch

```
cluster = ECSCluster(cluster_arn="<CLUSTER_ARN>", image="<ECR IMAGE>", 
    vpc="<VPC_ID>", subnets=[<SUBNETS>], security_groups=[<SG>])
```
and the error 

```
Exception ignored in: <function Cluster.__del__ at 0x7f812a004ca0>
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 107, in __del__
    if self.status != Status.closed:
AttributeError: 'ECSCluster' object has no attribute 'status'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 727, in __init__
    super().__init__(**kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/distributed/deploy/spec.py", line 276, in __init__
    self.sync(self._start)
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 183, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 924, in _start
    await super()._start()
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/distributed/deploy/spec.py", line 304, in _start
    self.scheduler = await self.scheduler
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 162, in _
    await self.start()
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 220, in start
    while timeout.run():
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/dask_cloudprovider/utils/timeout.py", line 74, in run
    raise self.exception
  File "/usr/local/Caskroom/miniconda/base/envs/aws/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 263, in start
    raise RuntimeError(response)  # print entire response
```

Thank you!

**Comment by jacobtomlinson** [comment]
Thanks for raising this @jkanche.

A couple of questions:
- That error looks like it happened on delete. So were you able to successfully create the cluster, but not delete it?
- Could you test dask-cloudprovider `0.4.1` to see if this is a regression in the latest release?
