### ISSUE TITLE
A cluster generated with the AzureVMCluster class crashes when submitting the documentation test function

### ISSUE THREAD

**Issue by manuelreyesgomez** [dask/dask-cloudprovider#201]
A cluster of Azure VMs was generated using the AzureVMCluster class

The cluster was generated as expected, as it could be corroborated in the Azure Portal

![VMList](https://user-images.githubusercontent.com/39012886/100679188-cd874b80-3323-11eb-8c13-ee6f1384cab4.png)

Following the basic example here: https://cloudprovider.dask.org/en/latest/azure.html#microsoft-azure

With variable cluster containing the Dask cluster

The following code was ran:

def get_gpu_model():
    import pynvml
    pynvml.nvmlInit()
    return pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))

from dask.distributed import Client
client = Client(cluster)

(At this point this warning is emitted)
C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\client.py:1129: VersionMismatchWarning: Mismatched versions found

Then running:

client.submit(get_gpu_model).result()

Produces the following errors

>>> client.submit(get_gpu_model).result()
distributed.protocol.pickle - INFO - Failed to deserialize b"\x80\x05\x95O\x03\x00\x00\x00\x00\x00\x00\x8c\x16tblib.pickling_support\x94\x8c\x12unpickle_exception\x94\x93\x94(\x8c\x08builtins\x94\x8c\tTypeError\x94\x93\x94\x8c'an integer is required (got type bytes)\x94\x85\x94Nh\x00\x8c\x12unpickle_traceback\x94\x93\x94\x8c\x05tblib\x94\x8c\x05Frame\x94\x93\x94)\x81\x94}\x94(\x8c\tf_globals\x94}\x94(\x8c\x08__name__\x94\x8c\x12distributed.worker\x94\x8c\x08__file__\x94\x8cH/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py\x94u\x8c\x06f_code\x94h\n\x8c\x04Code\x94\x93\x94)\x81\x94}\x94(\x8c\x0bco_filename\x94h\x14\x8c\x07co_name\x94\x8c\x10ensure_computing\x94ububM\xb6\th\n\x8c\tTraceback\x94\x93\x94)\x81\x94}\x94(\x8c\x08tb_frame\x94h\x0c)\x81\x94}\x94(h\x0f}\x94(h\x11h\x12h\x13h\x14uh\x15h\x17)\x81\x94}\x94(h\x1ah\x14h\x1b\x8c\x17_maybe_deserialize_task\x94ubub\x8c\ttb_lineno\x94M\x8d\t\x8c\x07tb_next\x94h\x1e)\x81\x94}\x94(h!h\x0c)\x81\x94}\x94(h\x0f}\x94(h\x11h\x12h\x13h\x14uh\x15h\x17)\x81\x94}\x94(h\x1ah\x14h\x1b\x8c\x0c_deserialize\x94ububh(M\xcf\x0ch)h\x1e)\x81\x94}\x94(h!h\x0c)\x81\x94}\x94(h\x0f}\x94(h\x11h\x12h\x13h\x14uh\x15h\x17)\x81\x94}\x94(h\x1ah\x14h\x1b\x8c\x0eloads_function\x94ububh(M\xc6\x0ch)h\x1e)\x81\x94}\x94(h!h\x0c)\x81\x94}\x94(h\x0f}\x94(h\x11\x8c\x1bdistributed.protocol.pickle\x94h\x13\x8cQ/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/protocol/pickle.py\x94uh\x15h\x17)\x81\x94}\x94(h\x1ah@h\x1b\x8c\x05loads\x94ububh(KKubububub\x87\x94R\x94t\x94R\x94."
Traceback (most recent call last):
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\protocol\pickle.py", line 75, in loads
    return pickle.loads(x)
ValueError: unsupported pickle protocol: 5
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\protocol\core.py", line 151, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\protocol\serialize.py", line 335, in deserialize
    return loads(header, frames)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\protocol\serialize.py", line 71, in pickle_loads
    return pickle.loads(x, buffers=buffers)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\protocol\pickle.py", line 75, in loads
    return pickle.loads(x)
ValueError: unsupported pickle protocol: 5
distributed.utils - ERROR - unsupported pickle protocol: 5
Traceback (most recent call last):
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\utils.py", line 655, in log_errors
    yield
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\client.py", line 1223, in _handle_report
    msgs = await self.scheduler_comm.comm.read()
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\comm\tcp.py", line 209, in read
    allow_offload=self.allow_offload,
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\comm\utils.py", line 87, in from_frames
    res = _from_frames()
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\comm\utils.py", line 66, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\protocol\core.py", line 151, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\protocol\serialize.py", line 335, in deserialize
    return loads(header, frames)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\protocol\serialize.py", line 71, in pickle_loads
    return pickle.loads(x, buffers=buffers)
  File "C:\Users\mreyesgomez\AppData\Local\Continuum\anaconda3\envs\AzureVMCluster\lib\site-packages\distributed\protocol\pickle.py", line 75, in loads
    return pickle.loads(x)
ValueError: unsupported pickle protocol: 5

Terminal just hangs after that

Screenshots:
![Screenshot (34)](https://user-images.githubusercontent.com/39012886/100679597-b09f4800-3324-11eb-8e93-0bbc0e05b6d9.png)

![Screenshot (35)](https://user-images.githubusercontent.com/39012886/100679860-48049b00-3325-11eb-9cf3-dd592f02e60a.png)

After doing ctrl-C

client.close() also throws errors

![Screenshot (36)](https://user-images.githubusercontent.com/39012886/100680137-ca8d5a80-3325-11eb-8af0-b44ad27a375e.png)

- Dask version: Latest version of dask cloud provider
- Python version: 3.79
- Operating System: Windows 10
- Install method (conda, pip, source): pip

**Comment by manuelreyesgomez** [comment]
From what I could find it seems to be a mismatch between python versions. I assumed it is between the version on the machine that launched the VM cluster and the image used on the scheduler and workers

**Comment by manuelreyesgomez** [comment]
That was the issue, error goes away when switching the base image to "rapidsai/rapidsai:cuda11.0-runtime-ubuntu18.04-py3.7" to match the python versions

**Comment by jacobtomlinson** [comment]
Thanks for following up with your solution here!
