### ISSUE TITLE
Running task on FargateCluster hangs indefinitely

### ISSUE THREAD

**Issue by ellbur** [dask/dask-cloudprovider#233]
**What happened**:

When I attempt to run a simple computation on a `FargateCluster`, the cluster is created, but the computation hangs indefinitely.

I can see the cluster in the AWS Console, with one task that appears to be the Dask scheduler task (container name `dask-scheduler`). No other tasks appear. 

I downloaded the `distributed` and `dask_cloudprovider` sources and would like to debug it to find where it hangs, if someone can point me to the places in the source where tasks are sent to the scheduler and that sort of thing. 

**Minimal Complete Verifiable Example**:

```python
from dask_cloudprovider.aws import FargateCluster
from distributed import Client

def do_work(n):
    return n + 1

if __name__ == '__main__':
    cluster = FargateCluster()
    client = Client(cluster)
    
    rs = client.gather(client.map(do_work, [ 1 ]))
    print(rs)
    
    client.close()
    cluster.close()
```

This produces the output:

```
/usr/lib/python3.8/contextlib.py:120: UserWarning: Creating your cluster is taking a surprisingly long time. This is likely due to pending resources on AWS. Hang tight! 
  next(self.gen)
/usr/local/lib/python3.8/dist-packages/distributed/client.py:1128: VersionMismatchWarning: Mismatched versions found

+---------+--------+-----------+---------+
| Package | client | scheduler | workers |
+---------+--------+-----------+---------+
| blosc   | None   | 1.9.2     | None    |
| lz4     | None   | 3.1.1     | None    |
| msgpack | 1.0.2  | 1.0.0     | None    |
+---------+--------+-----------+---------+
Notes: 
-  msgpack: Variation is ok, as long as everything is above 0.6
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
```

When I interrupt it, it produces the stack trace:

```
Traceback (most recent call last):
  File "test-1.py", line 15, in <module>
    rs = client.gather(client.map(do_work, [ 1 ]))
  File "/usr/local/lib/python3.8/dist-packages/distributed/client.py", line 1985, in gather
    return self.sync(
  File "/usr/local/lib/python3.8/dist-packages/distributed/client.py", line 831, in sync
    return sync(
  File "/usr/local/lib/python3.8/dist-packages/distributed/utils.py", line 337, in sync
    e.wait(10)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.8.6
- Operating System: Ubuntu amd64
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
You are not creating any workers, so no work will ever be executed.

You need to call `cluster.scale(n)` where `n` is the number of workers you want, or alternatively you can call `cluster.adapt()` which will create and destroy workers on the fly when tasks are submitted.

**Comment by ellbur** [comment]
Oh is that all. Now I feel silly. But yes, this works:

```python

def do_work(n):
    return n + 1

if __name__ == '__main__':
    from dask_cloudprovider.aws import FargateCluster
    from distributed import Client
    
    cluster = FargateCluster()
    cluster.adapt(minimum=0, maximum=100)
    
    client = Client(cluster)
    
    rs = client.gather(client.map(do_work, [ 1 ]))
    print(rs)
    
    client.close()
    cluster.close()
```

**Comment by jacobtomlinson** [comment]
Don't feel silly, it wasn't clear from the docs. I'll be sure to add some more examples.
