### ISSUE TITLE
RuntimeError("IOLoop is closed") error generated when creating FargateCluster via Prefect DaskExecutor

### ISSUE THREAD

**Issue by benwolz** [dask/dask-cloudprovider#242]
**What happened**:
When using the DaskExecutor to run a Prefect Flow, the cluster is created successfully, but on completion of the flow a series of RuntimeErrors are thrown and the cluster is not removed from ECS.

**What you expected to happen**:
DaskExecutor creates a dask cluster (works), runs a flow on said cluster (works), and tears it down upon completion (does not work).

**Minimal Complete Verifiable Example**:
code:

```python
import prefect
from prefect import Flow, task, Parameter

from prefect.run_configs import LocalRun
from prefect.executors import DaskExecutor
from prefect.executors import LocalDaskExecutor
from prefect.executors import LocalExecutor
from prefect.storage import GitHub

from dask_cloudprovider.aws import FargateCluster

import time

FARGATE_EXECUTOR = DaskExecutor(
    cluster_class="dask_cloudprovider.aws.FargateCluster",
    cluster_kwargs={
        "image": "prefecthq/prefect:latest",
        "n_workers": 1,
        "scheduler_cpu": 256,
        "scheduler_mem": 512,
        "worker_cpu": 256,
        "worker_mem": 512,
        "scheduler_timeout": "5 minutes",
        "execution_role_arn": "arn:aws:iam::[[IAM ID]]:role/ecsTaskExecutionRole-DaskAccess",
    }
)

@task
def times_two(x):
    # time.sleep(20)
    print("TIMES TWO COMPLETE")
    return x * 2

@task
def square(x):
    print("SQUARE COMPLETE")
    return x ** 2


with Flow("Control Script", executor=FARGATE_EXECUTOR) as flow:
    print("Setting up Flow")
    x = Parameter("x", default=3)
    y = times_two(x)
    results = square(y)

if __name__ == "__main__":
    print("Starting Flow")
    flow.run()
    print("Flow Complete")
```
error trace:

```python-traceback
C:\Users\benda\Anaconda3\envs\prefect-ecs\python.exe C:/Users/benda/Desktop/reboot-motion/dockerized-control-script/tmp.py
Setting up Flow
Starting Flow
[2021-01-26 11:00:40-0500] INFO - prefect.FlowRunner | Beginning Flow run for 'Control Script'
C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\contextlib.py:119: UserWarning: Creating your cluster is taking a surprisingly long time. This is likely due to pending resources on AWS. Hang tight! 
  next(self.gen)
C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\client.py:1133: VersionMismatchWarning: Mismatched versions found

+---------+--------+-----------+---------+
| Package | client | scheduler | workers |
+---------+--------+-----------+---------+
| numpy   | 1.19.5 | None      | None    |
+---------+--------+-----------+---------+
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
[2021-01-26 11:02:54-0500] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
Traceback (most recent call last):
Flow Complete
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\deploy\cluster.py", line 183, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\utils.py", line 305, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
Traceback (most recent call last):
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\deploy\cluster.py", line 183, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\utils.py", line 305, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
Traceback (most recent call last):
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\deploy\cluster.py", line 183, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\utils.py", line 305, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
Traceback (most recent call last):
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\deploy\cluster.py", line 183, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\utils.py", line 305, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
Traceback (most recent call last):
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\deploy\cluster.py", line 183, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\benda\Anaconda3\envs\prefect-ecs\lib\site-packages\distributed\utils.py", line 305, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed

Process finished with exit code 0
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.1.0
- Python version: 3.7.9
- Operating System: Windows
- Install method (conda, pip, source): conda virtual environment

**Comment by jacobtomlinson** [comment]
Thanks for taking the time to raise this but I think you need to raise this with Prefect.

If you are able to reproduce with a pure `dask_cloudprovider` example without Prefect we would be happy to investigate.

**Comment by EmilRex** [comment]
Wanted to share a few tips that I encountered while looking into this issue:
1. When using the `DaskTaskRunner`, only tasks that are invoked with `.submit()` are scheduled on Dask. Invoking the task function directly causes it to be executed locally.
2. Any Dask nodes must have Prefect installed. Note that the `daskdev/dask` image exposes an `EXTRA_PIP_PACKAGES` environment variable that can be used for this.
3. Any Dask nodes will crash unless they're pointed at Prefect Cloud or another accessible Orion instance (at least using the `daskdev/dask` image). Effectively this means that `PREFECT_API_KEY` and `PREFECT_API_URL` should be set in the environment.
4. Using an image hosted on public DockerHub with ECS FARGATE seemingly always results in [getting rate limited](https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/).
