### ISSUE TITLE
Specification of required permissions for deploying Dask Cluster on GCP

### ISSUE THREAD

**Issue by joyofdata** [dask/dask-cloudprovider#279]
Hello!

If I'm not mistaken then there is no documentation regarding the required permissions for the Service Account used for deploying the Dask cluster on GCP.

With regard to deploying a cluster using the following code:

```python
# SA: export GOOGLE_APPLICATION_CREDENTIALS="/home/raffael/repos/dask/playground-310111-1d035231463d.json"

from dask_cloudprovider.gcp import GCPCluster

cluster = GCPCluster(
    projectid="playground-310111", 
    n_workers=1, 
    source_image="projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20210325",
    zone="europe-west1-b",
)
```
That deployment succeeds if I attach the Project Owner role to the Service Account but fails with Compute Admin role.
Using the Project Owner role would obviously be not very satisfying (principle of least privilege).

It would be interesting to know what permissions are required.

Regards

Raffael

**Comment by joyofdata** [comment]
Compute Admin role + **Service Account User** role works. 

Next question would be how to replace Compute Admin role with something less powerful / more specific.

**Comment by jacobtomlinson** [comment]
I agree it would be good to document the required permissions for all cluster managers. I think we only have this for `ECSCluster`/`FargateCluster` today.

Poking through the code here the only call we make with the `googleapiclient` are:
- Suthenticate with service account or user credentials
- Create a VM
- List VMs
- Delete a VM

**Comment by jacobtomlinson** [comment]
@joyofdata could you share what error you get when only using a Compute Admin role.

**Comment by joyofdata** [comment]
> @joyofdata could you share what error you get when only using a Compute Admin role.

```
Launching cluster with the following configuration: 
  Source Image: projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20210325 
  Docker Image: daskdev/dask:latest 
  Machine Type: n2-standard-2 
  Filesytsem Size: 50 
  Disk Type: pd-standard 
  N-GPU Type:  
  Zone: europe-west1-b 
Creating scheduler instance

Cloud init
==========

#cloud-config

# Bootstrap
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - ubuntu-drivers-common

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]


runcmd:
  
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker

  # Run container
  - 'docker run --net=host   daskdev/dask:latest env DASK_INTERNAL_INHERIT_CONFIG="eyJ0...ZX19" python -m distributed.cli.dask_scheduler'

  # Shutdown when command is done
  - shutdown -h now
  
Failed to find running VMI...
{'id': 'projects/playground-xyz/zones/europe-west1-b/instances', 'selfLink': 'https://www.googleapis.com/compute/v1/projects/playground-xyz/zones/europe-west1-b/instances', 'kind': 'compute#instanceList'}
Traceback (most recent call last):
  File "gcp_cluster.py", line 13, in <module>
    cluster = GCPCluster(
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/dask_cloudprovider/gcp/instances.py", line 603, in __init__
    super().__init__(debug=debug, **kwargs)
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/dask_cloudprovider/generic/vmcluster.py", line 289, in __init__
    super().__init__(**kwargs, security=self.security)
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/distributed/deploy/spec.py", line 282, in __init__
    self.sync(self._start)
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 188, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "/home/raffael/.local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/dask_cloudprovider/generic/vmcluster.py", line 329, in _start
    await super()._start()
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/distributed/deploy/spec.py", line 311, in _start
    self.scheduler = await self.scheduler
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/distributed/deploy/spec.py", line 71, in _
    await self.start()
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/dask_cloudprovider/gcp/instances.py", line 283, in start
    await self.start_scheduler()
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/dask_cloudprovider/gcp/instances.py", line 298, in start_scheduler
    self.internal_ip, self.external_ip = await self.create_vm()
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/dask_cloudprovider/gcp/instances.py", line 209, in create_vm
    while await self.update_status() != "RUNNING":
  File "/home/raffael/miniconda3/envs/dask/lib/python3.8/site-packages/dask_cloudprovider/gcp/instances.py", line 255, in update_status
    raise Exception(f"Missing Instance {self.name}")
Exception: Missing Instance dask-111071f6-scheduler
```

**Comment by jacobtomlinson** [comment]
And when you ran that did you see the scheduler VM get created in the GCP console?

**Comment by joyofdata** [comment]
> And when you ran that did you see the scheduler VM get created in the GCP console?

Using only Compute Admin role and [above code](https://github.com/dask/dask-cloudprovider/issues/279#issuecomment-817658276) will cause the instance to be launched and immediately being stopped.

By trial and error I found the following list of required permissions which seem to be sufficient for creating a cluster (again - using [above code](https://github.com/dask/dask-cloudprovider/issues/279#issuecomment-817658276)) together with Service Account User role:

- compute.disks.create
- compute.disks.delete
- compute.disks.get
- compute.disks.list
- compute.instances.create
- compute.instances.delete
- compute.instances.get
- compute.instances.list
- compute.instances.setLabels
- compute.instances.setMetadata
- compute.instances.setServiceAccount
- compute.instances.setTags
- compute.subnetworks.use
- compute.subnetworks.useExternalIp

**Comment by jacobtomlinson** [comment]
Thanks for gathing that list, it's really helpful. I'm just a little confused because the Compute Admin role has `compute.*` permissions, so that should include everything you listed.

Are there any error messages on the stopped instance?

**Comment by joyofdata** [comment]
> Thanks for gathing that list, it's really helpful. I'm just a little confused because the Compute Admin role has `compute.*` permissions, so that should include everything you listed.
> 
> Are there any error messages on the stopped instance?

But Service Account User role isn't a subset of Compute Admin role. 

- Compute Admin role: doesn't work
- Service Account User role + Compute Admin role: works
- Service Account User role + [above list]: seems to work

**Comment by heiqs** [comment]
I am facing with similar issue. Only scheduler works and no worker can be spawned. I set the roles as suggested above, but no success. There is no error in cloud-init-output log file.

**Comment by jacobtomlinson** [comment]
That's great, thanks for digging into this.

Do you have any interest in raising a PR to document this?
