### ISSUE TITLE
FargateCluster timeout (ThrottlingException) on cluster creattion

### ISSUE THREAD

**Issue by nmerket** [dask/dask-cloudprovider#309]
**What happened**:

I went to start a `FargateCluster` and after while, got the following error:

```
Task exception was never retrieved
future: <Task finished name='Task-10603' coro=<_wrap_awaitable() done, defined at /opt/conda/lib/python3.8/asyncio/tasks.py:688> exception=ClientError('An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded')>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 163, in _
    await self.start()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 289, in start
    if not await self._task_is_running():
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 216, in _task_is_running
    await self._update_task()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 185, in _update_task
    await ecs.describe_tasks(
  File "/opt/conda/lib/python3.8/site-packages/aiobotocore/client.py", line 155, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded
Task exception was never retrieved
future: <Task finished name='Task-10658' coro=<_wrap_awaitable() done, defined at /opt/conda/lib/python3.8/asyncio/tasks.py:688> exception=ClientError('An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded')>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 163, in _
    await self.start()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 309, in start
    await self._set_address_from_logs()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 210, in _set_address_from_logs
    if not await self._task_is_running():
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 216, in _task_is_running
    await self._update_task()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 185, in _update_task
    await ecs.describe_tasks(
  File "/opt/conda/lib/python3.8/site-packages/aiobotocore/client.py", line 155, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded
Task exception was never retrieved
future: <Task finished name='Task-10581' coro=<_wrap_awaitable() done, defined at /opt/conda/lib/python3.8/asyncio/tasks.py:688> exception=ClientError('An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded')>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 163, in _
    await self.start()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 289, in start
    if not await self._task_is_running():
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 216, in _task_is_running
    await self._update_task()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 185, in _update_task
    await ecs.describe_tasks(
  File "/opt/conda/lib/python3.8/site-packages/aiobotocore/client.py", line 155, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded
Task exception was never retrieved
future: <Task finished name='Task-10659' coro=<_wrap_awaitable() done, defined at /opt/conda/lib/python3.8/asyncio/tasks.py:688> exception=ClientError('An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded')>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 163, in _
    await self.start()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 289, in start
    if not await self._task_is_running():
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 216, in _task_is_running
    await self._update_task()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 185, in _update_task
    await ecs.describe_tasks(
  File "/opt/conda/lib/python3.8/site-packages/aiobotocore/client.py", line 155, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded
Task exception was never retrieved
future: <Task finished name='Task-10656' coro=<_wrap_awaitable() done, defined at /opt/conda/lib/python3.8/asyncio/tasks.py:688> exception=ClientError('An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded')>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 163, in _
    await self.start()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 289, in start
    if not await self._task_is_running():
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 216, in _task_is_running
    await self._update_task()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 185, in _update_task
    await ecs.describe_tasks(
  File "/opt/conda/lib/python3.8/site-packages/aiobotocore/client.py", line 155, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded
Task exception was never retrieved
future: <Task finished name='Task-10612' coro=<_wrap_awaitable() done, defined at /opt/conda/lib/python3.8/asyncio/tasks.py:688> exception=ClientError('An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded')>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 163, in _
    await self.start()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 289, in start
    if not await self._task_is_running():
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 216, in _task_is_running
    await self._update_task()
  File "/opt/conda/lib/python3.8/site-packages/dask_cloudprovider/aws/ecs.py", line 185, in _update_task
    await ecs.describe_tasks(
  File "/opt/conda/lib/python3.8/site-packages/aiobotocore/client.py", line 155, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the DescribeTasks operation (reached max retries: 4): Rate exceeded
```

When I look in ECS, the tasks are all there and running. 

**What you expected to happen**:

A cluster to be created. 

**Minimal Complete Verifiable Example**:

```python
cluster = FargateCluster(
    region_name='us-west-2',
    n_workers=80,
    scheduler_cpu=2048,
    scheduler_mem=8192,
    worker_cpu=4*1024,
    worker_mem=30*1024,
    worker_extra_args=['--nthreads', '2'],
    scheduler_timeout='1 hour',
    task_role_policies=[
        'arn:aws:iam::aws:policy/AmazonS3FullAccess'
    ],
)```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.8.1, dask-cloudprovider=2021.6.0
- Python version: 3.8.10
- Operating System: docker image daskdev/dask:2021.8.1
- Install method (conda, pip, source): conda

**Comment by jacobtomlinson** [comment]
Thanks for raising this. I had hoped we had fixed this in #124.

**Comment by nmerket** [comment]
Thanks for looking into it @jacobtomlinson. It's been pointed out to me that this is a pretty big cluster. My current workaround is to start a smaller cluster (10 workers) and then scale it up once its running. I still get the occasional timeout error, but it seems to work well enough for our purposes.

**Comment by nmerket** [comment]
@jacobtomlinson I'm still running into a similar error in other parts of my workflow. It's always a `ThrottlingException` raised by `_update_task`. It looks like #124 wraps around `_update_task` to back off as necessary, for that one case but there are three other locations where it is called and can hit that exception. What do you think about moving the backoff code _inside_ `_update_task`? I think that would avoid some more of these errors.
