### ISSUE TITLE
Certificate Verify Failed on ECSCluster 

### ISSUE THREAD

**Issue by wfclark5** [dask/dask-cloudprovider#327]
**Description**
An attempt was made to create a Dask cluster on ECS with ECSCluster. I am receiving an SSL certificate verification error. Typically I solve this by providing the session created by aibotocore with the parameter "use_ssl=False". I have done so with s3fs in the past.

```
s3fs.S3FileSystem(use_ssl=False)
``` 

That doesn't seem to be an option so I tried setting the security argument to False as provided in the documentation but that also does not seem to work. 

**Example**
```python 
from dask_cloudprovider.aws import ECSCluster

cluster = ECSCluster(cluster_arn="my cluster", security=False)
```

**What happened**:

Traceback (most recent call last):
```
  File "/home/wfclark5/miniconda3/envs/ops_dev/lib/python3.6/site-packages/aiohttp/connector.py", line 985, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/home/wfclark5/miniconda3/envs/ops_dev/lib/python3.6/asyncio/base_events.py", line 824, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/home/wfclark5/miniconda3/envs/ops_dev/lib/python3.6/asyncio/base_events.py", line 850, in _create_connection_transport
    yield from waiter
  File "/home/wfclark5/miniconda3/envs/ops_dev/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/home/wfclark5/miniconda3/envs/ops_dev/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/home/wfclark5/miniconda3/envs/ops_dev/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
```
**What you expected to happen**:

Make an attempt to create a Dask cluster on ECS. 

**Anything else we need to know?**: 

Behind a firewall that doesn't allow for SSL, so disabling SSL is a requirement for local development. 

**Environment**:

- Dask version: '2021.03.0'
- Dask Cloud Provider version: '0.5.0'
- Python version: 3.6.13
- Operating System: Ubuntu-18.04 (local)
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
Thanks for raising this. I guess we should add a `use_ssl` option and pass that through to boto. Do you have any interest in raising a PR to add this?

**Comment by wfclark5** [comment]
Absolutely! I'll give it a shot! Any initial direction would be helpful!

**Comment by jacobtomlinson** [comment]
Great!

I expect you'll want to:
- Add a kwarg to the [cluster manager](https://github.com/dask/dask-cloudprovider/blob/876ccbabff2063e6629219fd5d381ead1c950ce7/dask_cloudprovider/aws/ecs.py#L458)
- Add the same option in the [config file](https://github.com/dask/dask-cloudprovider/blob/main/dask_cloudprovider/cloudprovider.yaml) with a default value
- Set an attribute with that option like [the others](https://github.com/dask/dask-cloudprovider/blob/main/dask_cloudprovider/aws/ecs.py#L873-L874)
- Set that option wherever a boot client is created.
