### ISSUE TITLE
Task creation errors masked by python unpack exception

### ISSUE THREAD

**Issue by kylejn27** [dask/dask-cloudprovider#33]
Upon task creation, cloudprovider attempts to unpack the tasks from the "tasks" selector into a list. It should check to see if "tasks" exists first, if not then it should check and print "failures" https://docs.aws.amazon.com/cli/latest/reference/ecs/run-task.html

Example Exception:

```Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /opt/conda/lib/python3.7/asyncio/tasks.py:596> exception=ValueError('not enough values to unpack (expected 1, got 0)')>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 603, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/conda/lib/python3.7/site-packages/dask_cloudprovider/providers/aws/ecs.py", line 120, in _
    await self.start()
  File "/opt/conda/lib/python3.7/site-packages/dask_cloudprovider/providers/aws/ecs.py", line 180, in start
    while timeout.run():
  File "/opt/conda/lib/python3.7/site-packages/dask_cloudprovider/utils/timeout.py", line 74, in run
    raise self.exception
  File "/opt/conda/lib/python3.7/site-packages/dask_cloudprovider/providers/aws/ecs.py", line 215, in start
    )["tasks"]
ValueError: not enough values to unpack (expected 1, got 0)```

**Comment by jacobtomlinson** [comment]
This looks like lazy coding on my part. We are assuming the `run_tasks` call succeeds and returns a list of one item.

For better error checking we should probably assign the response to a variable and do proper error checking on that, and then grab the element out of the list.

```python
# Replace this
[self.task] = await self._clients["ecs"].run_task( ...

# with this
resp = await self._clients["ecs"].run_task( ...
# do some error checking
[self.task] = resp
```


Do you have interest in putting in a PR for this?
