### ISSUE TITLE
Proposal: New implementation of ECSCluster

### ISSUE THREAD

**Issue by kinghuang** [dask/dask-cloudprovider#330]
I use `ECSCluster` heavily, but I find it has lots of small implementation issues that make it hard to reliably run large Dask clusters. Here's a laundry list of some of the problems I've run into.

* Task names are always derived from the cluster name. In a shared ECS cluster, task definitions overlap between multiple ECSCluster instances, making it impossible to tell what tasks belong to which Dask cluster.
* API rate limits are not handled properly. Combined with the log parsing for addresses (relates to #313, #121), large clusters are hard to reliably instantiate because the worker IP addresses can't be found.
* ECSCluster directly instantiates tasks without using a service. There's no good way to do placement strategies like binpack.
* Exited tasks are not handled and rescheduled. When workers run on spot instances, the Dask cluster can gradually lose workers as spot instances come and go.
* There's no way to configure capacity providers for tasks.
* There's no way to configure different subnets, environment variables, etc. for schedulers vs workers.
* Scaling a cluster while a previous scale is still in progress sometimes fails.
* Too many IAM permissions are required, even when using pre-existing ECS clusters and resources.
* Deprovisioning of tasks for both workers and schedulers is not clean (relates to #262).
* Closing the client and cluster objects results in dangling hooks.

Rather than trying to morph the existing `ECSCluster` class, would this project be open to a completely new implementation (`ECSCluster2`?). I anticipate API changes are required (i.e., the arguments to `ECSCluster`). I'm willing to tackle this myself.

**Comment by jacobtomlinson** [comment]
If you are willing to take on this work I'd be very happy to review and test it. 

A new implementation sounds reasonable. A good approach could be to open some PRS to start adding a new class and then at some point when it is feature compatible with the existing one we will switch them out. I'm not too worried about a breaking change at some point, folks can always pin versions. We did something similar with `SSHCluster` over in distributed a while back.

**Comment by kinghuang** [comment]
> If you are willing to take on this work I'd be very happy to review and test it.

Cool, I will get started on this soon. And, I'm going to collect some stack traces in the meantime for future reference.

**Comment by kinghuang** [comment]
Assorted exceptions.

<details>
<summary>
ThrottlingException when calling ListAccountSettings
</summary>

```
Task exception was never retrieved
future: <Task finished name='Task-1375' coro=<_wrap_awaitable() done, defined at /usr/local/lib/python3.9/asyncio/tasks.py:685> exception=ClientError('An error occurred (ThrottlingException) when calling the ListAccountSettings operation (reached max retries: 4): Rate exceeded')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/usr/local/lib/python3.9/site-packages/dask_cloudprovider/aws/ecs.py", line 163, in _
    await self.start()
  File "/usr/local/lib/python3.9/site-packages/dask_cloudprovider/aws/ecs.py", line 232, in start
    while timeout.run():
  File "/usr/local/lib/python3.9/site-packages/dask_cloudprovider/utils/timeout.py", line 74, in run
    raise self.exception
  File "/usr/local/lib/python3.9/site-packages/dask_cloudprovider/aws/ecs.py", line 237, in start
    if await self._is_long_arn_format_enabled():
  File "/usr/local/lib/python3.9/site-packages/dask_cloudprovider/aws/ecs.py", line 176, in _is_long_arn_format_enabled
    await ecs.list_account_settings(
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/client.py", line 155, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the ListAccountSettings operation (reached max retries: 4): Rate exceeded
```
</details>
