### ISSUE TITLE
dask cluster errors when adaptive scaling is enabled with a custom scheduler

### ISSUE THREAD

**Issue by jkanche** [dask/dask-cloudprovider#346]

**Comment by jacobtomlinson** [comment]
Apologies for the delay in responding here, it dropped off my radar. This definitely seems like a `dask-cloudprovider` issue.

It seems like the `SchedulerAddress` class should be an awaitable object. We can make it one by adding an `__await__` method to it like we do in the actual scheduler object.

https://github.com/dask/dask-cloudprovider/blob/a9d4c5143e4a7491787efd8b8c05e68b5813bfc6/dask_cloudprovider/aws/ecs.py#L167-L175

**Comment by jacobtomlinson** [comment]
@jkanche could you try out the fix in #347 and let me know if that solves things for you?

**Comment by jkanche** [comment]
cool, that works. @jacobtomlinson is it possible to publish a new release version of this package ?

**Comment by jkanche** [comment]
@jacobtomlinson or @quasiben a follow up error shows up in the logs

```
| 1657166131225 | tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fe80c83a520>>, <Task finished name='Task-13485' coro=<AdaptiveCore.__init__.<locals>._adapt() done, defined at /opt/conda/lib/python3.8/site-packages/distributed/deploy/adaptive_core.py:119> exception=AttributeError("'SchedulerAddress' object has no attribute 'status'")>) |
| 1657166131225 | Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 1657166131225 |   File "/opt/conda/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback                                                                                                                                                                                                                                                                                                                                                            |
| 1657166131225 |     ret = callback()                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 1657166131225 |   File "/opt/conda/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result                                                                                                                                                                                                                                                                                                                                                   |
| 1657166131225 |     future.result()                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| 1657166131225 |   File "/opt/conda/lib/python3.8/site-packages/distributed/deploy/adaptive_core.py", line 122, in _adapt                                                                                                                                                                                                                                                                                                                                                 |
| 1657166131225 |     await core.adapt()                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 1657166131225 |   File "/opt/conda/lib/python3.8/site-packages/distributed/deploy/adaptive_core.py", line 240, in adapt                                                                                                                                                                                                                                                                                                                                                  |
| 1657166131225 |     await self.scale_down(**recommendations)                                                                                                                                                                                                                                                                                                                                                                                                             |
| 1657166131225 |   File "/opt/conda/lib/python3.8/site-packages/distributed/deploy/adaptive.py", line 201, in scale_down                                                                                                                                                                                                                                                                                                                                                  |
| 1657166131225 |     await f                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 1657166131225 |   File "/opt/conda/lib/python3.8/site-packages/distributed/deploy/spec.py", line 532, in scale_down                                                                                                                                                                                                                                                                                                                                                      |
| 1657166131225 |     await self                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 1657166131225 |   File "/opt/conda/lib/python3.8/site-packages/distributed/deploy/spec.py", line 379, in _                                                                                                                                                                                                                                                                                                                                                               |
| 1657166131225 |     await self._correct_state()                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 1657166131225 |   File "/opt/conda/lib/python3.8/site-packages/distributed/deploy/spec.py", line 316, in _correct_state_internal                                                                                                                                                                                                                                                                                                                                         |
| 1657166131225 |     if self.scheduler.status == Status.running:                                                                                                                                                                                                                                                                                                                                                                                                          |
| 1657166131225 | AttributeError: 'SchedulerAddress' object has no attribute 'status'                                                                                                                                                                                                                                                                                                                                                                                      
```
