### ISSUE TITLE
Execution fails when importing from a different module

### ISSUE THREAD

**Issue by dandavison** [dask/dask-cloudprovider#68]
I have a minimal example of a `dask.bag` map executing on Fargate involving two modules. When I run the module in which the task and map are defined, everything works correctly. When I attempt to import the function from a second module, it fails.

When I use a plain `Client()` rather than `Client(FargateCluster(n_workers=1))`, everything works as expected, leading me to infer that the problem lies with `dask-cloudprovider`, or at least the way in which I am using it.

I've tried `dask-cloudprovider==0.1.1` and also installing from master.

This repo contains everything needed to reproduce the problem I'm describing: https://github.com/dandavison/dask-cloud-provider-problem and I will repeat the problem description here:

I have one file named `dask_cloudprovider_bug_minimal_example.py`:

```python
import dask.bag

def task(i):
    return i + 1

def run_tasks():
    print(dask.bag.from_sequence(range(10)).map(task).compute())

if __name__ == "__main__":
    from dask_cloudprovider import FargateCluster
    from dask.distributed import Client

    Client(FargateCluster(n_workers=1))
    run_tasks()  # WORKS
```

I have a second file named `dask_cloudprovider_bug_minimal_example_importer.py`:

```python
import dask_cloudprovider_bug_minimal_example

if __name__ == "__main__":
    from dask_cloudprovider import FargateCluster
    from dask.distributed import Client

    Client(FargateCluster(n_workers=1))
    dask_cloudprovider_bug_minimal_example.run_tasks()  # ERROR!
    # distributed.scheduler.KilledWorker: ("('task-94b724e41a5f306a008072467f552008', 8)", <Worker 'tcp://172.31.62.150:35627', name: 0, memory: 0, processing: 10>)
```

`python dask_cloudprovider_bug_minimal_example.py` works as expected, executing on Fargate and printing out `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`.

`python dask_cloudprovider_bug_minimal_example_importer.py` fails as follows:

```
Traceback (most recent call last):
  File "dask_cloudprovider_bug_minimal_example_importer.py", line 8, in <module>
    dask_cloudprovider_bug_minimal_example.run_tasks()  # DNW!
  File "/Users/dan/src/dask_cloudprovider_bug/dask_cloudprovider_bug_minimal_example.py", line 9, in run_tasks
    print(dask.bag.from_sequence(range(10)).map(task).compute())
  File "/Users/dan/src/dask_cloudprovider_bug/.venv2/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/dan/src/dask_cloudprovider_bug/.venv2/lib/python3.7/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/dan/src/dask_cloudprovider_bug/.venv2/lib/python3.7/site-packages/distributed/client.py", line 2595, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/Users/dan/src/dask_cloudprovider_bug/.venv2/lib/python3.7/site-packages/distributed/client.py", line 1893, in gather
    asynchronous=asynchronous,
  File "/Users/dan/src/dask_cloudprovider_bug/.venv2/lib/python3.7/site-packages/distributed/client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/Users/dan/src/dask_cloudprovider_bug/.venv2/lib/python3.7/site-packages/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/Users/dan/src/dask_cloudprovider_bug/.venv2/lib/python3.7/site-packages/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/Users/dan/src/dask_cloudprovider_bug/.venv2/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/dan/src/dask_cloudprovider_bug/.venv2/lib/python3.7/site-packages/distributed/client.py", line 1752, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ("('task-94b724e41a5f306a008072467f552008', 8)", <Worker 'tcp://172.31.62.150:35627', name: 0, memory: 0, processing: 10>)
distributed.client - ERROR - Failed to reconnect to scheduler after 10.00 seconds, closing client
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
concurrent.futures._base.CancelledError
```

Thanks very much for all the work on this project and dask in general!

**Comment by dandavison** [comment]
Thanks @martindurant who pointed out elsewhere that this problem occurs because I had taken no steps to ensure the imported module was present on the workers: it can be solved by calling [upload_file](https://distributed.dask.org/en/latest/api.html#distributed.Client.upload_file).

Specifically, the toy example above can be fixed by making the two files into a python package and modifying `dask_cloudprovider_bug_minimal_example_importer.py as follows:

```python
from pathlib import Path                                                                                                                                                                                     
                                                                                                                                                                                                              
 from dask_cloudprovider_problem import dask_cloudprovider_bug_minimal_example                                                                                                                                
                                                                                                                                                                                                              
 if __name__ == "__main__":                                                                                                                                                                                   
     from dask_cloudprovider import FargateCluster                                                                                                                                                            
     from dask.distributed import Client                                                                                                                                                                      
                                                                                                                                                                                                              
     egg_file = Path("__file__").parent / "dist" / "dask_cloudprovider_problem-0.0.0-py3.7.egg"                                                                                                               
     assert egg_file.exists()                                                                                                                                                                                 
     client = Client(FargateCluster(n_workers=1))                                                                                                                                                             
     client.upload_file(egg_file)                                                                                                                                                                             
     dask_cloudprovider_bug_minimal_example.run_tasks()
```
