### ISSUE TITLE
'NoneType' object has no attribute 'close' on ECS initalization

### ISSUE THREAD

**Issue by JulianWgs** [dask/dask-cloudprovider#89]
Hello,

I'm having trouble initializing a dask cluster on ECS.

```python
from dask_cloudprovider import ECSCluster
cluster = ECSCluster(
    cluster_arn="XXX",
)
```

Initialization works fine, when using Fargate.

Versions:
dask: 1.14.0
distributed: 1.14.0
dask-cloudprovider: 0.2.0

Might be related to this: https://github.com/rapidsai/dask-cuda/issues/251

```python
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x7fb720067630>>, <Task finished coro=<SpecCluster._close() done, defined at /home/XXX/.local/lib/python3.6/site-packages/distributed/deploy/spec.py:373> exception=AttributeError("'NoneType' object has no attribute 'close'",)>)
Traceback (most recent call last):
  File "/home/XXX/.local/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/XXX/.local/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/XXX/.local/lib/python3.6/site-packages/distributed/deploy/spec.py", line 386, in _close
    await self.scheduler_comm.close(close_workers=True)
AttributeError: 'NoneType' object has no attribute 'close'

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-27-f4e11de8e9d9> in <module>
      3     scheduler_mem=2048,
      4     worker_mem=2048,
----> 5     security_groups=["sg-02e663e52b96eca0a"]
      6 
      7 )

~/.local/lib/python3.6/site-packages/dask_cloudprovider/providers/aws/ecs.py in __init__(self, fargate_scheduler, fargate_workers, image, scheduler_cpu, scheduler_mem, scheduler_timeout, worker_cpu, worker_mem, worker_gpu, n_workers, cluster_arn, cluster_name_template, execution_role_arn, task_role_arn, task_role_policies, cloudwatch_logs_group, cloudwatch_logs_stream_prefix, cloudwatch_logs_default_retention, vpc, subnets, security_groups, environment, tags, find_address_timeout, skip_cleanup, aws_access_key_id, aws_secret_access_key, region_name, **kwargs)
    597         self._lock = asyncio.Lock()
    598         self.session = aiobotocore.get_session()
--> 599         super().__init__(**kwargs)
    600 
    601     def _client(self, name: str):

~/.local/lib/python3.6/site-packages/distributed/deploy/spec.py in __init__(self, workers, scheduler, worker, asynchronous, loop, security, silence_logs, name)
    254         if not self.asynchronous:
    255             self._loop_runner.start()
--> 256             self.sync(self._start)
    257             self.sync(self._correct_state)
    258 

~/.local/lib/python3.6/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    160         else:
    161             return sync(self.loop, func, *args, **kwargs)
--> 162 
    163     async def _get_logs(self, scheduler=True, workers=True):
    164         logs = Logs()

~/.local/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    332             result[0] = yield future
    333         except Exception as exc:
--> 334             error[0] = sys.exc_info()
    335         finally:
    336             thread_state.asynchronous = False

~/.local/lib/python3.6/site-packages/distributed/utils.py in f()
    316 
    317     e = threading.Event()
--> 318     main_tid = threading.get_ident()
    319     result = [None]
    320     error = [False]

~/.local/lib/python3.6/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/.local/lib/python3.6/site-packages/dask_cloudprovider/providers/aws/ecs.py in _start(self)
    770             "Hang tight! ",
    771         ):
--> 772             await super()._start()
    773 
    774     @property

~/.local/lib/python3.6/site-packages/distributed/deploy/spec.py in _start(self)
    282 
    283         self.status = "starting"
--> 284         self.scheduler = await self.scheduler
    285         self.scheduler_comm = rpc(
    286             getattr(self.scheduler, "external_address", None) or self.scheduler.address,

~/.local/lib/python3.6/site-packages/dask_cloudprovider/providers/aws/ecs.py in _()
    128             async with self.lock:
    129                 if not self.task:
--> 130                     await self.start()
    131                     assert self.task
    132             return self

~/.local/lib/python3.6/site-packages/dask_cloudprovider/providers/aws/ecs.py in start(self)
    193     async def start(self):
    194         timeout = Timeout(60, "Unable to start %s after 60 seconds" % self.task_type)
--> 195         while timeout.run():
    196             try:
    197                 kwargs = (

~/.local/lib/python3.6/site-packages/dask_cloudprovider/utils/timeout.py in run(self)
     72                 return False
     73             else:
---> 74                 raise self.exception
     75         return True
     76 

~/.local/lib/python3.6/site-packages/dask_cloudprovider/providers/aws/ecs.py in start(self)
    230 
    231                 if not response.get("tasks"):
--> 232                     raise RuntimeError(response)  # print entire response
    233 
    234                 [self.task] = response["tasks"]

RuntimeError: {'tasks': [], 'failures': {'arn': 'XXX:XXX:XXX:XX-XXXXXXX-X:XXXXXXXXXXXX:XXXXXXXXX-XXXXXXXX/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', 'reason': 'ATTRIBUTE'}, 'ResponseMetadata': {'RequestId': 'f53e623a-bc99-4488-a8ec-74d34703c090', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', 'content-type': 'application/x-amz-json-1.1', 'content-length': '275', 'date': 'XXX, XX XXX XXXX XX:XX:XX XXX'}, 'RetryAttempts': 0}}



```

**Comment by mrocklin** [comment]
The warning given in the title of this issue isn't the main point.  It's
just that things didn't start up properly, and so when it closed down it
was confused.  I've improved the warning message here:
https://github.com/dask/distributed/pull/3735

For the actual ECS error message that you're getting (this is the
RuntimeError at the bottom of your post) I don't personally know what's
going on, but hopefully someone else can help here.

**Comment by martindurant** [comment]
Note that the main maintainer of this repo is currently on leave, so it might take longer for you to get a diagnosis of the problem.

Meanwhile:
> Initialization works fine

Doo you mean initialisation of your container, of did you actually get a working dask cluster up to the time of the error?

**Comment by JulianWgs** [comment]
Thanks for the help!

I can initialize, scale and run calculation on a Fargate cluster. (I want to use GPUs so I can't use that)

The error is produced, when running the above code snippet and the `ECSCluster` function doesn't return anything. I don't think, I have a working dask cluster afterwards, but how exactly would I check? Running the code again (with a provided security group, because it was already created), yields the same error.

Greetings

**Comment by jacobtomlinson** [comment]
@JulianWgs given that you have switched to EKS I'm going to close this out. But if anyone else is having the same problem please comment and I'll reopen it.
